# Generated by Django 4.0.3 on 2022-05-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text="Email field can't be empty!", max_length=254, unique=True)),
                ('handyman_image', models.ImageField(blank=True, null=True, upload_to='handymanimages')),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('handyman_rating', models.FloatField(default=0)),
                ('handyman_rating_count', models.IntegerField(default=0)),
                ('handyman_services', models.CharField(choices=[('Painting', 'Painting'), ('Delevery Services', 'Delevery Services'), ('Furniture Assembly', 'Furniture Assembly'), ('General Handyman', 'General Handyman'), ('Help Moving', 'Help Moving'), ('TV Mounting', 'TV Mounting'), ('Gardening and Removal', 'Gardening and Removing'), ('Disinfecting Services', 'Disinfecting Services'), ('Hang Pictures', 'Hang Pictures'), ('IKEA Services', 'IKEA Services'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('All Services', 'All Services')], default='All Services', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('service_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_FixR', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Custom Users',
            },
        ),
        migrations.CreateModel(
            name='servicemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('Painting', 'Painting'), ('Delevery Services', 'Delevery Services'), ('Furniture Assembly', 'Furniture Assembly'), ('General Handyman', 'General Handyman'), ('Help Moving', 'Help Moving'), ('TV Mounting', 'TV Mounting'), ('Gardening and Removal', 'Gardening and Removing'), ('Disinfecting Services', 'Disinfecting Services'), ('Hang Pictures', 'Hang Pictures'), ('IKEA Services', 'IKEA Services'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('All Services', 'All Services')], default='All Services', max_length=100)),
                ('category', models.CharField(choices=[('Delevery Services', 'Delevery Services'), ('Furniture Assembly', 'Furniture Assembly'), ('General Handyman', 'General Handyman'), ('Help Moving', 'Help Moving'), ('TV Mounting', 'TV Mounting'), ('Gardening and Removal', 'Gardening and Removing'), ('Disinfecting Services', 'Disinfecting Services'), ('Hang Pictures', 'Hang Pictures'), ('IKEA Services', 'IKEA Services'), ('All Category', 'All Category')], default='All Category', max_length=100)),
                ('hoursneeded', models.IntegerField(default=1)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('service_images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.CharField(help_text='Description is required.', max_length=500)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_int', models.FloatField(default=0)),
                ('FixR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FixR_rating', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursneeded', models.IntegerField(default=2, verbose_name='Hours Needed')),
                ('duedate', models.DateField(verbose_name='Select Date')),
                ('time', models.TimeField(verbose_name='Select Time')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Describe Your Task')),
                ('service_images', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image of Task')),
                ('date_time_created', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('FixR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_handyman', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
