# Generated by Django 4.0.3 on 2022-05-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rating_int',
        ),
    ]
