# Generated by Django 4.0.3 on 2022-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0002_alter_rate_options_remove_rate_rating_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
