# Generated by Django 4.0.3 on 2022-05-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0003_booked_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booked',
            options={'ordering': ('duedate',), 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='booked',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
